version: '3'
services:
  web-redirect:
    image: adamkdean/redirect
    environment:
      VIRTUAL_HOST: skimo.pl
      LETSENCRYPT_HOST: skimo.pl
      LETSENCRYPT_EMAIL: "dariusz.finster@gmail.com"
      REDIRECT_LOCATION: "https://www.skimo.pl"
    networks:
      service_network:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    volumes:
      - nginx-conf:./docker/web/app.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5433"
  web:
    expose:
     - 3000
    environment:
      - RAILS_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - HTTP_PORT=3000
      - VIRTUAL_HOST=www.skimo.pl
      - LETSENCRYPT_HOST=www.skimo.pl
      - LETSENCRYPT_EMAIL="dariusz.finster@gmail.com"
    networks:
      service_network:
    image: regedarek/skimoapp-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/var/www/skimoapp
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db

networks:
  service_network:

volumes:
  app:
  db_data:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-conf:
