version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    image: regedarek/skimoapp-web
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=db-host
    ports:
      - "5432:5432"
  app:
    environment:
        - SECRET_TOKEN=tessfsdf
        - RAILS_ENV=production
        - RACK_ENV=production
    image: regedarek/skimoapp-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/docker-rails
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
volumes:
  web:
  db:
