version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    image: regedarek/skimoapp-web
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5433"
  app:
    environment:
      - RAILS_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    image: regedarek/skimoapp-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/var/www/skimoapp
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
volumes:
  app:
  db_data:
