default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV['DB_HOST'] %>
  adapter:  <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %> 

development:
  adapter: sqlite3
  database: db/beer_development.sqlite3

test:
  adapter: sqlite3
  database: db/beer_test.sqlite3

production:
  <<: *default
  database: docker_rails_production

