production:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
  openstack_username: <%= ENV["OPENSTACK_USERNAME"] %>
  openstack_api_key: <%= ENV["OPENSTACK_API_KEY"] %>
  openstack_temp_url_key: <%= ENV["OPENSTACK_TEMP_KEY"] %>
