test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

openstack:
  service: OpenStack
  container: "skimoapp-cloud-production" # Container name for your OpenStack provider
  credentials:
    openstack_auth_url: "https://auth.cloud.ovh.net/"
    openstack_username: <%= ENV["OPENSTACK_USERNAME"] %>
    openstack_api_key: <%= ENV["OPENSTACK_API_KEY"] %>
    openstack_region: 'WAW'
    openstack_temp_url_key: <%= ENV["OPENSTACK_TEMP_KEY"] %>
  connection_options: # optional
    chunk_size: 2097152 # 2MBs - 1MB is the default

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
